CREATE TABLE PESSOA(
	PESSOA_ID INTEGER NOT NULL,
	NOME VARCHAR2(250) NOT NULL,
	TIPO_FISICA NUMBER(1,0) NOT NULL,
	CPF VARCHAR2(250),
	DATA_NASCIMENTO timestamp with time zone,
	CNPJ VARCHAR2(250),
	RAZAO_SOCIAL VARCHAR2(250),
    PRIMARY KEY (PESSOA_ID)
);
CREATE SEQUENCE PESSOA_ID_SEQ START WITH 1;
