CREATE TABLE CONTA(
	CONTA_ID INTEGER NOT NULL,
	PESSOA_ID INTEGER NOT NULL,
	NOME VARCHAR2(250) NOT NULL,
	SALDO VARCHAR2(250) NOT NULL,
	DATA_CRIACAO timestamp with time zone NOT NULL,
	FOREIGN KEY(PESSOA_ID) REFERENCES PESSOA (PESSOA_ID),
    PRIMARY KEY (CONTA_ID)
);

CREATE SEQUENCE CONTA_ID_SEQ START WITH 1;
